name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
    env:n      OANDA_TOKEN: ${{ secrets.OANDA_TOKEN }}n      OANDA_ACCOUNT_ID: ${{ secrets.OANDA_ACCOUNT_ID }}
      - run: python -m pip install -r requirements.txt
      - run: python -m pip install pytest
      - run: pytest -q
      - run: ruff check .n      - run: mypy .n      - name: Build Docker imagen        run: docker build -t fxbot:ci .
