---
name: docker-build

on:
  push:
    tags: ['v*']            # 例: v0.1.3 を push すると実行
  pull_request:             # PR を開く／更新すると実行
  workflow_dispatch:        # 「Run workflow」ボタンで手動実行

jobs:
  build-multiarch:
    runs-on: ubuntu-latest

    # Package 書き込みだけを許可（最小権限）
    permissions:
      contents: read
      packages: write

    steps:
      # 1) ソース取得（完全履歴）
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) pip wheel キャッシュ
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      # 3) QEMU（クロスビルド用エミュレーター）
      - uses: docker/setup-qemu-action@v3

      # 4) Buildx をセットアップ
      - uses: docker/setup-buildx-action@v3

      # 5) GHCR にログイン
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}   # repo → “Packages: write” 権限を付与

      # 6) マルチアーキテクトでビルド & プッシュ
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false                  # SBOM 不要なら false が高速
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
