name: Docker Publish
on:
  push:
    tags: ["v*"]
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/${{ github.repository_owner }}/fxbot:${{ github.ref_name }} .
      - run: docker push ghcr.io/${{ github.repository_owner }}/fxbot:${{ github.ref_name }}
