name: docs-pages
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docs
        run: |
          pip install -r requirements.txt sphinx sphinx-rtd-theme
          sphinx-build -b html docs docs/_build/html
      - uses: actions/upload-pages-artifact@v3
        with: {path: docs/_build/html}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: {pages: write, id-token: write}
    environment: {name: github-pages}
    steps:
      - uses: actions/deploy-pages@v4
