name: Deploy Docs
on:
  push:
    branches: [master]

permissions:
  contents: write      # gh-pages へ push するので必須

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Sphinx
        run: |
          pip install -r requirements.txt sphinx sphinx-rtd-theme
          sphinx-build -b html docs docs/_build/html
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
